# Generated by Django 3.1.3 on 2020-11-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('DNI', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('movil', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('dia', models.CharField(max_length=10)),
                ('h_inicio', models.TimeField()),
                ('h_fin', models.TimeField()),
                ('grupo', models.CharField(max_length=10)),
                ('profe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.profesores')),
            ],
        ),
    ]
