# Generated by Django 3.1.3 on 2020-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('dia', models.CharField(max_length=10)),
                ('h_inicio', models.TimeField()),
                ('h_fin', models.TimeField()),
                ('grupo', models.CharField(max_length=10)),
                ('profe', models.CharField(max_length=10)),
            ],
        ),
    ]
