# Generated by Django 3.1.3 on 2020-11-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_spreadsheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpreadSheet',
        ),
    ]
