# Generated by Django 3.1.3 on 2020-11-24 12:37

from django.db import migrations, models
import gsheets.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_delete_spreadsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('dia', models.CharField(max_length=10)),
                ('h_inicio', models.TimeField()),
                ('h_fin', models.TimeField()),
                ('grupo', models.CharField(max_length=10)),
                ('profe', models.CharField(max_length=10)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
    ]
